### ISSUE TITLE
댓글 작성이 되지 않는 것 같습니다. ㅠㅠ

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [Leop0ld/leop0ld.github.com#8]
- 댓글 작성시 아래의 에러가 뜨네요 ㅠㅠ
>Error: utterances is not installed on leop0ld/blog. If you own this repo, [install the app](https://github.com/apps/utterances). Read more about this change in [the PR](https://github.com/utterance/utterances/pull/25).

**Comment by myungseokang** [comment]
헛 알겠습니다 ㅠㅠ 알려주셔서 감사합니다!

**Comment by rohjaeseok** [comment]
저도 똑같은 메시지인데..왜안되는걸까요??
